@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=2 graphs...
echo Processing bck2217 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\bck2217.par
echo Processing bcl380 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\bcl380.par
echo Processing bva2144 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\bva2144.par
echo Processing dbj2924 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dbj2924.par
echo Processing dca1389 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dca1389.par
echo Processing dcb2086 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dcb2086.par
echo Processing dcc1911 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dcc1911.par
echo Processing dea2382 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dea2382.par
echo Processing dja1436 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dja1436.par
echo Processing djb2036 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\djb2036.par
echo Processing djc1785 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\djc1785.par
echo Processing dka1376 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dka1376.par
echo Processing dkd1973 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dkd1973.par
echo Processing dkg813 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dkg813.par
echo Processing fnb1615 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\fnb1615.par
echo Processing fra1488 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\fra1488.par
echo Processing gr666 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\gr666.par
echo Processing icw1483 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\icw1483.par
echo Processing irw2802 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\irw2802.par
echo Processing ley2323 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\ley2323.par
echo Processing lim963 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\lim963.par
echo Processing pa561 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pa561.par
echo Processing pbk411 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pbk411.par
echo Processing pbl395 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pbl395.par
echo Processing pbm436 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pbm436.par
echo Processing pbn423 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pbn423.par
echo Processing pcb442 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pcb442.par
echo Processing pia3056 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pia3056.par
echo Processing pka379 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pka379.par
echo Processing rbu737 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\rbu737.par
echo Processing rbv1583 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\rbv1583.par
echo Processing rbx711 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\rbx711.par
echo Processing rby1599 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\rby1599.par
echo Processing xit1083 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\xit1083.par
echo Processing xpr2308 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\xpr2308.par
echo Processing xqc2175 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\xqc2175.par
echo Processing xql662 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\xql662.par
echo Finished k=2 graphs.
pause
