@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=15 graphs...
echo Processing bcl380 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\bcl380.par
echo Processing dkg813 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\dkg813.par
echo Processing gr666 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\gr666.par
echo Processing pa561 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\pa561.par
echo Processing pbk411 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\pbk411.par
echo Processing pbl395 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\pbl395.par
echo Processing pbm436 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\pbm436.par
echo Processing pbn423 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\pbn423.par
echo Processing pcb442 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\pcb442.par
echo Processing pka379 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\pka379.par
echo Processing rbu737 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\rbu737.par
echo Processing rbx711 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\rbx711.par
echo Processing xql662 (k=15)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k15\xql662.par
echo Finished k=15 graphs.
pause
