@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=25 graphs...
echo Processing bcl380 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\bcl380.par
echo Processing dkg813 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\dkg813.par
echo Processing gr666 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\gr666.par
echo Processing pa561 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\pa561.par
echo Processing pbk411 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\pbk411.par
echo Processing pbl395 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\pbl395.par
echo Processing pbm436 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\pbm436.par
echo Processing pbn423 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\pbn423.par
echo Processing pcb442 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\pcb442.par
echo Processing pka379 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\pka379.par
echo Processing rbu737 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\rbu737.par
echo Processing rbx711 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\rbx711.par
echo Processing xql662 (k=25)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k25\xql662.par
echo Finished k=25 graphs.
pause
