@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=10 graphs...
echo Processing bcl380 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\bcl380.par
echo Processing dkg813 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\dkg813.par
echo Processing gr666 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\gr666.par
echo Processing pa561 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\pa561.par
echo Processing pbk411 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\pbk411.par
echo Processing pbl395 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\pbl395.par
echo Processing pbm436 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\pbm436.par
echo Processing pbn423 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\pbn423.par
echo Processing pcb442 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\pcb442.par
echo Processing pka379 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\pka379.par
echo Processing rbu737 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\rbu737.par
echo Processing rbx711 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\rbx711.par
echo Processing xql662 (k=10)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k10\xql662.par
echo Finished k=10 graphs.
pause
