@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=20 graphs...
echo Processing bcl380 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\bcl380.par
echo Processing dkg813 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\dkg813.par
echo Processing gr666 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\gr666.par
echo Processing pa561 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\pa561.par
echo Processing pbk411 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\pbk411.par
echo Processing pbl395 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\pbl395.par
echo Processing pbm436 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\pbm436.par
echo Processing pbn423 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\pbn423.par
echo Processing pcb442 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\pcb442.par
echo Processing pka379 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\pka379.par
echo Processing rbu737 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\rbu737.par
echo Processing rbx711 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\rbx711.par
echo Processing xql662 (k=20)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k20\xql662.par
echo Finished k=20 graphs.
pause
