@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=4 graphs...
echo Processing bcl380 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\bcl380.par
echo Processing dkg813 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\dkg813.par
echo Processing gr666 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\gr666.par
echo Processing pa561 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\pa561.par
echo Processing pbk411 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\pbk411.par
echo Processing pbl395 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\pbl395.par
echo Processing pbm436 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\pbm436.par
echo Processing pbn423 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\pbn423.par
echo Processing pcb442 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\pcb442.par
echo Processing pka379 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\pka379.par
echo Processing rbu737 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\rbu737.par
echo Processing rbx711 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\rbx711.par
echo Processing xql662 (k=4)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k4\xql662.par
echo Finished k=4 graphs.
pause
