@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on FULL graphs...
echo Processing bck2217...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\bck2217.par
echo Processing bcl380...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\bcl380.par
echo Processing bva2144...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\bva2144.par
echo Processing dbj2924...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dbj2924.par
echo Processing dca1389...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dca1389.par
echo Processing dcb2086...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dcb2086.par
echo Processing dcc1911...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dcc1911.par
echo Processing dea2382...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dea2382.par
echo Processing dja1436...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dja1436.par
echo Processing djb2036...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\djb2036.par
echo Processing djc1785...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\djc1785.par
echo Processing dka1376...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dka1376.par
echo Processing dkd1973...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dkd1973.par
echo Processing dkg813...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dkg813.par
echo Processing fnb1615...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\fnb1615.par
echo Processing fra1488...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\fra1488.par
echo Processing gr666...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\gr666.par
echo Processing icw1483...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\icw1483.par
echo Processing irw2802...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\irw2802.par
echo Processing ley2323...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\ley2323.par
echo Processing lim963...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\lim963.par
echo Processing pa561...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pa561.par
echo Processing pbk411...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pbk411.par
echo Processing pbl395...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pbl395.par
echo Processing pbm436...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pbm436.par
echo Processing pbn423...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pbn423.par
echo Processing pcb442...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pcb442.par
echo Processing pia3056...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pia3056.par
echo Processing pka379...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pka379.par
echo Processing rbu737...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\rbu737.par
echo Processing rbv1583...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\rbv1583.par
echo Processing rbx711...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\rbx711.par
echo Processing rby1599...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\rby1599.par
echo Processing xit1083...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\xit1083.par
echo Processing xpr2308...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\xpr2308.par
echo Processing xqc2175...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\xqc2175.par
echo Processing xql662...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\xql662.par
echo Finished FULL graphs.
pause
