@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=3 graphs...
echo Processing bcl380 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\bcl380.par
echo Processing dkg813 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\dkg813.par
echo Processing gr666 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\gr666.par
echo Processing pa561 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\pa561.par
echo Processing pbk411 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\pbk411.par
echo Processing pbl395 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\pbl395.par
echo Processing pbm436 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\pbm436.par
echo Processing pbn423 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\pbn423.par
echo Processing pcb442 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\pcb442.par
echo Processing pka379 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\pka379.par
echo Processing rbu737 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\rbu737.par
echo Processing rbx711 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\rbx711.par
echo Processing xql662 (k=3)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k3\xql662.par
echo Finished k=3 graphs.
pause
