@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=2 graphs...
echo Processing bcl380 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\bcl380.par
echo Processing dkg813 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\dkg813.par
echo Processing gr666 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\gr666.par
echo Processing pa561 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pa561.par
echo Processing pbk411 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pbk411.par
echo Processing pbl395 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pbl395.par
echo Processing pbm436 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pbm436.par
echo Processing pbn423 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pbn423.par
echo Processing pcb442 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pcb442.par
echo Processing pka379 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\pka379.par
echo Processing rbu737 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\rbu737.par
echo Processing rbx711 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\rbx711.par
echo Processing xql662 (k=2)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k2\xql662.par
echo Finished k=2 graphs.
pause
