@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=8 graphs...
echo Processing bck2217 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\bck2217.par
echo Processing bcl380 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\bcl380.par
echo Processing bva2144 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\bva2144.par
echo Processing dbj2924 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dbj2924.par
echo Processing dca1389 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dca1389.par
echo Processing dcb2086 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dcb2086.par
echo Processing dcc1911 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dcc1911.par
echo Processing dea2382 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dea2382.par
echo Processing dja1436 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dja1436.par
echo Processing djb2036 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\djb2036.par
echo Processing djc1785 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\djc1785.par
echo Processing dka1376 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dka1376.par
echo Processing dkd1973 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dkd1973.par
echo Processing dkg813 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dkg813.par
echo Processing fnb1615 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\fnb1615.par
echo Processing fra1488 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\fra1488.par
echo Processing gr666 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\gr666.par
echo Processing icw1483 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\icw1483.par
echo Processing irw2802 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\irw2802.par
echo Processing ley2323 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\ley2323.par
echo Processing lim963 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\lim963.par
echo Processing pa561 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pa561.par
echo Processing pbk411 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pbk411.par
echo Processing pbl395 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pbl395.par
echo Processing pbm436 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pbm436.par
echo Processing pbn423 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pbn423.par
echo Processing pcb442 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pcb442.par
echo Processing pia3056 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pia3056.par
echo Processing pka379 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pka379.par
echo Processing rbu737 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\rbu737.par
echo Processing rbv1583 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\rbv1583.par
echo Processing rbx711 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\rbx711.par
echo Processing rby1599 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\rby1599.par
echo Processing xit1083 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\xit1083.par
echo Processing xpr2308 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\xpr2308.par
echo Processing xqc2175 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\xqc2175.par
echo Processing xql662 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\xql662.par
echo Finished k=8 graphs.
pause
