@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running ALL LKH experiments...

echo 1. Running FULL graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_full.bat"

echo 2.2. Running k=2 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k2.bat"

echo 2.3. Running k=3 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k3.bat"

echo 2.4. Running k=4 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k4.bat"

echo 2.5. Running k=5 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k5.bat"

echo 2.6. Running k=6 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k6.bat"

echo 2.7. Running k=7 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k7.bat"

echo 2.8. Running k=8 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k8.bat"

echo 2.10. Running k=10 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k10.bat"

echo 2.12. Running k=12 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k12.bat"

echo 2.15. Running k=15 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k15.bat"

echo 2.20. Running k=20 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k20.bat"

echo 2.25. Running k=25 graphs...
call "C:\Users\user\Desktop\SeniorProject_step1\parameters\run_k25.bat"

echo ALL experiments completed!
pause
