@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=7 graphs...
echo Processing bcl380 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\bcl380.par
echo Processing dkg813 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\dkg813.par
echo Processing gr666 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\gr666.par
echo Processing pa561 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\pa561.par
echo Processing pbk411 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\pbk411.par
echo Processing pbl395 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\pbl395.par
echo Processing pbm436 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\pbm436.par
echo Processing pbn423 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\pbn423.par
echo Processing pcb442 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\pcb442.par
echo Processing pka379 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\pka379.par
echo Processing rbu737 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\rbu737.par
echo Processing rbx711 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\rbx711.par
echo Processing xql662 (k=7)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k7\xql662.par
echo Finished k=7 graphs.
pause
