@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=8 graphs...
echo Processing bcl380 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\bcl380.par
echo Processing dkg813 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\dkg813.par
echo Processing gr666 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\gr666.par
echo Processing pa561 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pa561.par
echo Processing pbk411 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pbk411.par
echo Processing pbl395 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pbl395.par
echo Processing pbm436 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pbm436.par
echo Processing pbn423 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pbn423.par
echo Processing pcb442 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pcb442.par
echo Processing pka379 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\pka379.par
echo Processing rbu737 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\rbu737.par
echo Processing rbx711 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\rbx711.par
echo Processing xql662 (k=8)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k8\xql662.par
echo Finished k=8 graphs.
pause
