@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on FULL graphs...
echo Processing bcl380...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\bcl380.par
echo Processing dkg813...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\dkg813.par
echo Processing gr666...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\gr666.par
echo Processing pa561...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pa561.par
echo Processing pbk411...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pbk411.par
echo Processing pbl395...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pbl395.par
echo Processing pbm436...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pbm436.par
echo Processing pbn423...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pbn423.par
echo Processing pcb442...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pcb442.par
echo Processing pka379...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\pka379.par
echo Processing rbu737...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\rbu737.par
echo Processing rbx711...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\rbx711.par
echo Processing xql662...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\full\xql662.par
echo Finished FULL graphs.
pause
