@echo off
cd C:\Users\user\Desktop\SeniorProject_step1
echo Running LKH on k=5 graphs...
echo Processing bcl380 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\bcl380.par
echo Processing dkg813 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\dkg813.par
echo Processing gr666 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\gr666.par
echo Processing pa561 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\pa561.par
echo Processing pbk411 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\pbk411.par
echo Processing pbl395 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\pbl395.par
echo Processing pbm436 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\pbm436.par
echo Processing pbn423 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\pbn423.par
echo Processing pcb442 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\pcb442.par
echo Processing pka379 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\pka379.par
echo Processing rbu737 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\rbu737.par
echo Processing rbx711 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\rbx711.par
echo Processing xql662 (k=5)...
"C:\LKH\LKH.exe" C:\Users\user\Desktop\SeniorProject_step1\parameters\k5\xql662.par
echo Finished k=5 graphs.
pause
